server:
  port: ${SERVER_PORT:5678}

feign:
  hystrix:
    enabled: true
     
eureka:
  client:
    enabled: false
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
#  instance:
#    #hostname: ${HOSTNAME:localhost}
#    preferIpAddress: true

#cloud:
#  conablefig:
#    failFast: true
#    discovery:
#      end: true
